// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djyjlnsiwvlkdztezkho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqeWpsbnNpd3Zsa2R6dGV6a2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTIyNDgsImV4cCI6MjA2NDE4ODI0OH0.L_J4JHh7Gxjqb1vky_PZ3AHyqe1LGLP9_7YKGh9LeQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);